main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('nfts/', views.nfts_index, name='index'),
    path('nfts/<int:nft_id>/', views.nfts_detail, name='detail'),
    path('nfts/create/', views.NFTCreate.as_view(), name="nfts_create"),
    path('nfts/<int:pk>/update/', views.NFTUpdate.as_view(), name='nfts_update'),
    path('nfts/<int:pk>/delete/', views.NFTDelete.as_view(), name='nfts_delete'),
    path('nfts/<int:nft_id>/add_listing/', views.add_listing, name='add_listing'),
]

nftcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

CRYPTOS = (
    ('B', 'Bitcoin'),
    ('E', 'Etherium'),
    ('S', 'Solana')
)

class NFT(models.Model):
    name = models.CharField(max_length=50)
    breed = models.CharField(max_length=100)
    traits = models.CharField(max_length=100)
    number = models.IntegerField()

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'nft_id': self.id})

class Listing(models.Model):
    market = models.CharField(max_length=15)
    crypto = models.CharField(
        max_length=1, 
            choices=CRYPTOS, 
            default=CRYPTOS[0][0]
    )

    nft = models.ForeignKey(NFT, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_crypto_display()} on {self.market}"

    class Meta:
        ordering = ['-market']

main_app/forms.py
from django.forms import ModelForm
from .models import Listing

class ListingForm(ModelForm):
  class Meta:
    model = Listing
    fields = ['market', 'crypto']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import NFT
from .forms import ListingForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def nfts_index(request):
    nfts = NFT.objects.all()
    return render(request, 'nfts/index.html', { 'nfts': nfts })

def nfts_detail(request, nft_id):
    nft = NFT.objects.get(id=nft_id)
    listing_form = ListingForm()
    # return render(request, 'nfts/detail.html', { 'nft': nft })
    return render(request, 'nfts/detail.html', {
      'nft': nft, 'listing_form': listing_form
})

def add_listing(request, nft_id):
  form = ListingForm(request.POST)
  if form.is_valid():
    new_listing = form.save(commit=False)
    new_listing.nft_id = nft_id
    new_listing.save()
  return redirect('detail', nft_id=nft_id)

class NFTCreate(CreateView):
  model = NFT
  fields = '__all__'
  success_url = '/nfts/'

class NFTUpdate(UpdateView):
  model = NFT
  fields = ['breed', 'traits', 'number']

class NFTDelete(DeleteView):
  model = NFT
  success_url = '/nfts/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About NFT's</h1>
A non-fungible token is a non-interchangeable unit of data stored on a blockchain, a form of digital ledger, that can be sold and traded. Types of NFT data units may be associated with digital files such as photos, videos, and audio.

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>NFT Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;NFTCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'nfts_create' %}">Add an NFT</a></li>
          <li><a href="{% url 'index' %}">View All My NFTs</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
{% block content %}
{% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 NFT Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}



{% endblock %}

main_app/templates/main_app/nft_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete NFT</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ nft.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' nft.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/nft_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{nft.name}}</span></h1>
{% else %}
  <h1>Add an NFT</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Add an NFT!" class="btn">
  </form>
{% endblock %}

main_app/templates/nfts/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>NFT Details</h1>

<div class="row">
  <div class="col s6">
    <form method="POST">
      {% csrf_token %}
      {{ listing_form.as_p }}
      <input type="submit" class="btn" value="Add Listing" name="market">
    </form>
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ nft.name }}</span>
        <p>Breed: {{ nft.breed }}</p>
        <p>Traits: {{ nft.traits }}</p>
        <p>Number: {{ nft.number }}</p>
      </div>
      <div class="card-action">
<div class="card-action">
  <a href="{% url 'nfts_update' nft.id %}">Edit</a>
  <a href="{% url 'nfts_delete' nft.id %}">Delete</a>
</div>
</div>
</div>
<div class="col s6">
<table class="striped">
  <thead>
    <tr><th>Market</th><th>Crypto</th></tr>
  </thead>
  <tbody>
    {% for listing in nft.listing_set.all %}
      <tr>
        <td>{{listing.market}}</td>
        <td>{{listing.get_market_display}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>
</div>
<script>
  const marketEl = document.getElementById('id_market');
  N.Marketpicker.init(marketEl);

  // add additional JS to initialize select below
  const selectEl = document.getElementById('id_crypto');
  N.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/nfts/index.html
{% extends 'base.html' %}
{% block content %}

<h1>NFT List</h1>
{% for nft in nfts %}
<a href="{% url 'detail' nft.id %}">
  <div class="card">
  <div class="card-content">
    <span class="card-title">{{ nft.name }}</span>
    <p>Breed: {{ nft.breed }}</p>
    <p>Traits: {{ nft.traits }}</p>
    <p>Number: {{ nft.number }}</p>
  </div>
</div>
{% endfor %}
{% endblock %}